# Generated by Django 6.0.1 on 2026-01-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_image',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_images/'),
        ),
    ]
