# Generated by Django 6.0.1 on 2026-01-23 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_department_id_alter_department_department_id'),
        ('subject', '0002_remove_subject_class_level_subject_class_level'),
        ('teacher', '0002_teacher_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='subject.subject'),
        ),
    ]
