# Generated by Django 6.0.1 on 2026-01-23 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_department_id_alter_department_department_id'),
        ('school', '0001_initial'),
        ('subject', '0001_initial'),
        ('teacher', '0002_teacher_teacher_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=10, unique=True)),
                ('section', models.CharField(max_length=5)),
                ('academic_year', models.DateField()),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department')),
                ('teachers', models.ManyToManyField(blank=True, to='teacher.teacher')),
            ],
            options={
                'ordering': ['academic_year', 'class_id', 'section'],
                'unique_together': {('class_id', 'section', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='ClassTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
            options={
                'verbose_name': 'Class Teacher Assignment',
                'verbose_name_plural': 'Class Teacher Assignments',
                'ordering': ['class_assigned', 'teacher', 'subject'],
                'unique_together': {('class_assigned', 'teacher', 'subject')},
            },
        ),
    ]
