# Generated by Django 6.0.1 on 2026-01-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_class_classteacherassignment'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='class_level',
        ),
        migrations.AddField(
            model_name='subject',
            name='class_level',
            field=models.ManyToManyField(blank=True, to='school.class'),
        ),
    ]
