# Generated by Django 6.0.1 on 2026-01-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('hod', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('no_of_students', models.IntegerField()),
            ],
        ),
    ]
