# Generated by Django 6.0.1 on 2026-01-18 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0003_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
