# Generated by Django 6.0.1 on 2026-01-18 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0004_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
