# Generated by Django 6.0.1 on 2026-01-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_passwordresetrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='N9y4N6xfHVVaSI4iIQdHMYE6jVRXFZWc', editable=False, max_length=32, unique=True),
        ),
    ]
