# Generated by Django 6.0.1 on 2026-01-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0007_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='tKzB1NnR6DdNuEzxnefhAIB5PPnGZn5S', editable=False, max_length=32, unique=True),
        ),
    ]
