# Generated by Django 6.0.1 on 2026-01-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0008_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='jeKc2CMkrdOilu8moAYkjTJkcLUSEeKz', editable=False, max_length=32, unique=True),
        ),
    ]
