# Generated by Django 6.0.1 on 2026-01-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0009_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='v1svd4ygSzFwGBxJL0ZC5EVPKErUnNIW', editable=False, max_length=32, unique=True),
        ),
    ]
