# Generated by Django 6.0.1 on 2026-01-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0011_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='2i2YOxBEeRGURNYVuHipdEmamCDBCsS1', editable=False, max_length=32, unique=True),
        ),
    ]
