# Generated by Django 6.0.1 on 2026-01-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0012_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='BbADBemqbPkf8x4tUiRcOGDVsiyjQJXk', editable=False, max_length=32, unique=True),
        ),
    ]
