# Generated by Django 6.0.1 on 2026-01-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0013_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='tBHDJMgMr4PJ6BNyM3zrCJfZsuvf65jA', editable=False, max_length=32, unique=True),
        ),
    ]
